name: Build and Deploy
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: ${{GIT_AUTHOR_NAME}}/tutor1@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run-script build
        AWS_DEFAULT_REGION: "us-east-1"
        LAMBDA_FUNC_NAME: ${{ secrets.FUNC_NAME }}
        STACK_NAME: ${{ secrets.STACK_NAME }}
        LAMBDA_HANDLER: "lambda/script"
        LAMBDA_MEMORY: 1024
        LAMBDA_TIMEOUT: 100
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
